version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: "always"
    network_mode: "host"
    volumes:
      - ./configuration/definitions.json:/etc/rabbitmq/definitions.json:Z
      - ./configuration/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:Z